- name: Ensure docker
  ansible.builtin.command: docker --version
  register: docker_info
  failed_when: false

- name: Docker setup
  when: docker_info.rc != 0
  block:
  - name: Install required packages
    ansible.builtin.apt:
      name:
        - ca-certificates
        - curl
      state: present
    become: true

  - name: Create /etc/apt/keyrings directory
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'
    become: true  

  - name: Download Docker's official GPG key
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: '0644'
    become: true

  - name: Get system architecture
    ansible.builtin.shell: dpkg --print-architecture
    register: system_architecture
    changed_when: false 

  - name: Add Docker repository to Apt sources
    ansible.builtin.apt_repository:
      repo: "deb [arch={{ system_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present
    become: true

  - name: Install Docker and related packages
    ansible.builtin.apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present
      update_cache: yes
    become: true

- name: adding existing user to group docker
  user:
    name: "{{ ansible_user_id  }}"
    groups: docker
    append: yes
  become: true

- name: Ensure Docker service configuration directory exists
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'
  become: true

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: Restart Docker service
  ansible.builtin.systemd:
    name: docker
    state: restarted
  become: true

- name: Ensure docker python module for Ansible
  ansible.builtin.apt:
    name: python3-docker
    state: present
  become: true

- name: Pull latest vmsifter image
  ansible.builtin.command: docker pull intel/vmsifter:latest
  # access denied when using community.docker.docker_image
  # community.docker.docker_image:
  #   name: vmsifter/vmsifter:latest
  #   source: pull
