name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  POETRY_VERSION: "2.1.1"

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        baseimage: ['python:3.13.2-slim-bookworm', 'pypy:3.11-7-slim-bookworm']
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5.1.0
        with:
          context: .
          tags: intel/vmsifter:latest
          target: vmsifter-dev
          build-args: |
            BASEIMAGE=${{ matrix.baseimage }}
            BUILD_ID=-ci-${{ github.run_id }}
          load: false
          # disable push for now.
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

  check:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        task: [format_check, lint, typing, unit_test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Poetry
        run: pip install poetry==${{ env.POETRY_VERSION }}

      - name: ${{ matrix.task }}
        run: |
          poetry install
          poetry run poe ${{ matrix.task }}
